#import "Conlang Template.typ": *
#import "@preview/leipzig-glossing:0.5.0": *
#import abbreviations: *
#import "my-abbreviations.typ": *

#show: doc => conf(
  doc,
  title: "Grammar of Proto-Lisian",
  subtitle: none,
  author: "StarDolphin5",
)

// ---------- CONTENT -----------
Copyright ©2025 by StarDolphin5. Available under a Creative Commons Attribution International (CC BY) 4.0 license (#link("https://creativecommons.org/licenses/by/4.0/")[link]). You are free to: Share — copy and redistribute the material in any medium or format; Adapt — remix, transform, and build upon the material; under the following terms:

- Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

#strong[Version 0.5.1] | Last updated on 2025-07-24

This grammar was made based on the "Conlang Grammar Template" by author J Rain De Jager, released in 2019 under a Creative Commons CC BY 4.0 license, which can be found on #link("https://www.overleaf.com/latex/templates/conlang-grammar-template/ysvrsjwftmfx").


= Introduction <introduction>
Proto-Lisian is a conlang serving as the ancestor of a family of languages originating in the midlands of the largest continent in my worldbuilding project with working name of Minglis.

The choice of the name "Proto-Lisian" is admittedly potentially problematic, as the modern-day Lisians are only one of the groups that spawned from the original speakers, and that the most culturally dominant group. Furthermore, Lisians don't identify by ethnicity but by covenantal religion, and in that framework, there are thousands of Lisians who don't natively speak any descendant of Proto-Lisian, and thousands of Proto-Lisian-descendant vernacular speakers who are not "Lisians". However, I make this choice because Proto-Lisian is the ancestor to Classical Lisian, the scriptural, liturgical, and literary language of the Lisians; given this is a worldbuilding project, the choice of name is therefore overtly in service of highlighting the Lisians' narrative prominence.

I can also be found as #link("https://www.reddit.com/user/MinervApollo/")[u/MinervApollo] on Reddit.

== Introduction to speakers
#lorem(15)

Linguistic and anthropological evidence suggests speakers of Proto-Lisian, like some of their modern counterparts, had fishing as a main economic activity and source of food.

== Theoretical framework
I am heavily indebted to #cite(<payne_describing_1997>, form: "prose") in the methodology for the layout of the grammar and what aspects of morphosyntax to pay attention to.

I adopt a Lexical Functional approach to morphosyntax, for which I refer to #cite(<dalrymple_handbook_2023>, form: "prose") as a general overview. For the annotated phrase structure rules and phrase structure trees, I use #cite(<lowe_minimal_2020>, form: "prose")'s Minimal Phrase Structure. I will also be making use of constructions as templates following #cite(<asudeh_constructions_2013>, form: "prose")'s proposal. For these constructions, I assume non-compositional meaning to be distributed among all the lexical entries generated by the lexicon, but for objections to this treatment, see Findlay (2023).

About information structure, I will not go beyond my limits, adopting wholesale both #cite(<gundel_cognitive_1993>, form: "prose")'s givenness hierarchy and #cite(<dalrymple_objects_2011>, form: "prose", supplement: [section 4.3])'s four-way distinction in information structure roles at s-structure and i-structure (through the features #FEAT[giv] and #FEAT[df], respectively) as sufficient for my description. A synthesis framework for information structure granularity is theoretically appropriate but beyond the scope of my knowledge; I suggest #cite(<dalrymple_oxford_2019>, form: "prose", supplement: [Ch. 10]) for a deeper discussion.

Finally, I adopt Glue semantics account of argument structure, as analyzed in #cite(<asudeh_flexible_2012>, form: "prose") and reviewed in #cite(<jamie_y_findlay_argument_2023>, form: "prose", supplement: "Chapter 6, Section 6.3").

== Structure of this grammar
Most sections of this document are divided into two parts: a main, descriptive section, which should be relatively accessible to anyone familiar with conlanging or linguistic conventions like the International Phonetic Alphabet (IPA) and the Leipzig Glossing Rules; and a "#THEX" subsection, where I go in depth into the formal analysis using the theoretical framework given above. This latter subsection is not required or expected to be read by the casual peruser and serves mainly as a playground to test my own theoretical understanding. However, those interested in the topic are welcome and invited to engage with it, for which I will devote a chapter to introduce the key concepts.

In #strong[@phonology], I give an overview of the phonological inventory of Proto-Lisian and the rules of word formation, otherwise known as phonotactics. It also introduces the orthography used throughout the rest of the grammar.

In #strong[@syntax], the main section of this grammar, I go not only into word order but explore the main constructions used in the language to express a wide range of meanings.

#include "chapters/phonology.typ"

= Syntax <syntax>
== Introduction
Proto-Lisian is broadly head-initial and has notably little inflectional morphology on non-verbs. Because of this, I describe constructions first and leave descriptions of the morphology, including the verbal paradigm and derivational morphology, to a later section.


== Basic order <word-order>
Basic word order is AVP/SV (aka SVO; I am using #cite(<payne_describing_1997>, form: "prose", supplement: [p. 75])'s terminology). Thus, a prototypical transitive sentence looks something like:
#numbered-example((
  source: ([Kùng], [gugesa], [ìf]),
  morphemes: ([woman], [see.#pst.#pfv], [man]),
  translation: [The/a woman saw the/a man.],
))

Similarly, an intransitive sentence can look like
#numbered-example((
  source: ([Lis], [gùgògàjà]),
  morphemes: ([Lis (name)], [cough.#pst.#pfv.#neg]),
  translation: [Lis didn't cough.],
))

=== #THEX
The former examples suggest the following phrase structure rules:

1. #PSR(
    2,
    3,
  )[N][V][#updownsubj][#UPDOWN][#extarg][#xhead][][(#MOTHERL #FEAT[cat]) = I]
// Optionality required in PSR 2 to allow for intransitive verbs
2. #PSR(2, 3)[V][(N)][#UPDOWN][(#UPARG[#FEAT[obj]])=#DOWN][#xhead][#intarg]

The annotation (#MOTHERL #FEAT[cat]) = I is adopted based on the analysis of topicalization and copulae, see below.

#include "chapters/adjectives.typ"

== Ditransitive clauses
For verbs of giving, the indirect object is placed after the verb but before the direct object, similar to English sentences like #E[I gave *Miriam* a rope]. An equivalent sentence in Proto-Lisian would look like:
#numbered-example((
  source: ([wa], [guolebi], [Miriam], [ludo]),
  morphemes: ([1#sg], [give.#pst.#pfv], [Miriam], [rope]),
  translation: [I gave Miriam a rope.],
))

=== #THEX

This suggests the existence of a PSR as such:

3. #PSR(
    3,
    3,
  )[V][N][N][#UPDOWN][#UPDOWNARG[#objtheta]][#UPDOWNARG[#FEAT[obj]]][#xhead][#intarg][#intarg]


== Topicalization and focus

Proto-Lisian allows for argument topicalization by fronting, allowing it for subjects, direct and oblique objects, and prepositional phrases, as in the following sentences:
#numbered-example((
  source: ([wa], [guolebi], [Miriam], [ludo]),
  morphemes: ([1#sg], [give.#pst.#pfv], [Miriam], [rope]),
  translation: [I gave Miriam a rope. (Unmarked or subject-topic)],
))
#numbered-example((
  source: ([ludo], [wa], [guolebi], [Miriam]),
  morphemes: ([rope], [1#sg], [give.#pst.#pfv], [Miriam]),
  translation: [The rope—I gave it to Miriam (Unmarked or subject-topic.)],
))
#numbered-example((
  source: ([ning], [owu], [ido], [làrà], [edi]),
  morphemes: ([#loc], [in], [lake], [#cop.#prs], [fish]),
  translation: [In the lake, there is a fish.],
))

Notably, the only exception seems to be the indirect object of verbs of giving, which may be a strategy to avoid ambiguity in sentences like:
#numbered-example((
  source: ([\*Miriam], [wa], [guolebi], [ludo]),
  morphemes: ([Miriam], [1#sg], [give.#pst.#pfv], [rope]),
  translation: (
    [Miriam—I gave the rope to her. OR The rope—I gave Miriam to it.]
  ),
))

It should be noted Proto-Lisian does not seem to have had any passivization mechanism. Instead, topicalization was used to raise objects and obliques to prominence, since phrase structure helps fix other arguments in place.

=== #THEX
This suggests the following:

#PSR(
  2,
  4,
)[{N | N | PP}][I][{(#UPARG[#FEAT[subj]]) = #DOWN | (#UPARG[#FEAT[obj]]) = #DOWN | {#UPARG[#objtheta] | #UP #objtheta} = #DOWN}][#UPDOWN][#extarg][#xhead][(#DOWNSIGMA #FEAT[df]) = #VAL[topic]][]

#include "chapters/predicate_nominals.typ"


== Noun incorporation <noun-incorporation>
Noun incorporation (NI) is a construction whereby "a N stem is compounded with a V stem to yield a larger, derived V stem" #cite(<mithun_evolution_1984>, supplement: [p. 1]). It is similar to compounds such as "babysitting" and "mountain-climbing" in English, although noun incorporation is a much more systematic and productive process. Here I adopt #cite(<mithun_evolution_1984>, form: "prose")'s four-way typology of NI which, in the words of Whimemsz as preserved in #cite(<lichen_the_fictioneer_conlang_2021>, form: "prose") "is probably close enough to the truth that it can be extremely useful to conlangers." It certainly is enough to explain phenomena in Proto-Lisian (of course, causation is in the opposite direction).

=== Type I Noun Incorporation
Type I NI is simple lexical compounding, where "The compound is more than a description; it is the name of an institutionalized activity or state. The [incorporated noun] loses its individual salience both semantically and syntactically. It no longer refers to a specific entity; instead, it simply narrows the scope of the V" #cite(<mithun_evolution_1984>, supplement: [p. 856]).

Proto-Lisian, demonstrating its consistent head initialness, has compounds like the following:
#numbered-example((
  source: ([-rum-akep-],),
  morphemes: ([drink-mead],),
  translation: [To drink (as in drink alcohol) (lit. "drink mead")],
))
#numbered-example(
  (
    source: ([Eko], [kù-mùg-edi-a]),
    morphemes: ([Eko], [#npst\-eat-fish-#real]),
    translation: [Eko is eating fish. / Eko eats fish.],
  ),
  label: "fisheat1",
)

To demonstrate the aforementioned distinction between noun incorporation and a straight sentence, compare @fisheat1 with @fisheat2:
#numbered-example(
  (
    source: ([Eko], [kù-mùg-à], [edi]),
    morphemes: ([Eko], [#npst\-eat-#real.#ipfv], [fish]),
    translation: [Eko is eating a fish.],
  ),
  label: "fisheat2",
)

In @fisheat2, Eko is eating a specific fish, or a whole fish; in @fisheat1, there is no specification as to how many or how much fish she is eating, or indeed if eating fish is instead a regular activity and not an instantiation of such.

#cite(<mithun_evolution_1984>, form: "author") notes "Since [incorporated nouns] do not refer to specific entities, these constructions tend to be used in contexts without specific, individuated patients. They may be generic statements; or descriptions of on-going activities, in which a patient has been incompletely affected; or habitual activities..."

Indeed, Proto-Lisian is very productive with these kinds of meanings; unlike #cite(<mithun_evolution_1984>, form: "author")'s earlier suggestion, the activity doesn't have to be institutionalized at all.


=== Type II Noun Incorporation
#strong[instrumental]
#numbered-example(
  (
    source: ([Èbèr], [wu-wi-ludo-i], [ìf]),
    morphemes: ([Èbèr], [#pfv\-tie.#pfv\-rope-#real], [man]),
    translation: [Èbèr tied the/a man with a rope.],
  ),
)


=== #THEX
Noun incorporation, especially type II NI, presents a special challenge to a theory like Lexical Functional Grammar, because a strongly held assumption of the theory is that syntax doesn't have access to the inside of words, also known as "strong lexicalism." #cite(<mithun_evolution_1984>, form: "author", supplement: [p. 847]), starting her abstract, calls NI "perhaps the most nearly syntactic of all morphological processes," due to its heavy modifications to verbal valency and semantics. In fact, LFG equipped with only c-structure and f-structure may not be able to capture the phenomenon properly.

This is one area where the strength of #cite(<asudeh_flexible_2012>, form: "prose")'s proposal shines through. With s-structure concerned with capturing the actual meaning intended to be conveyed, f-structure can be allowed to do its job capturing functional-syntactic information.

Specifically, we can propose that the lexicon, which is generative in its own right, actually composes the meanings of the N and the V into one lexical entry with the appropriate adjusted valency. This distinguishes, for example, the following (for simplicity, we ignore information structure and assume progressive aspect):

#grid(
  columns: 3,
  rows: auto,
  gutter: 0.75em,
  [kùmùgà], [V], [(#UPARG[pred]) = 'eat'],
  [], [], [#TEMPL[\@present]],
  [], [], [#TEMPL[\@progressive]],
  [],
  [],
  [$
      lambda x lambda y lambda e. op("eat")(e) and op("agent")(e,x) and op("patient")(e,y)
      :\
      #UPARGSIGMA[subj] multimap #UPARGSIGMA[obj] multimap (#UPSIGMA #FEAT[event]) multimap #UPSIGMA
    $],
)

#grid(
  columns: 3,
  rows: auto,
  gutter: 0.75em,
  [edi], [N], [(#UPARG[pred]) = 'eat'],
  [], [], [(#UPSIGMA #FEAT[giv]) $gt.eq$ #VAL[referential]],
  [], [], [$"fish" : #UPSIGMA$],
)

And:

#grid(
  columns: 3,
  rows: auto,
  gutter: 0.75em,
  [kùmùgedia], [V], [(#UPARG[pred]) = 'eat-fish'],
  [], [], [#TEMPL[\@present]],
  [], [], [#TEMPL[\@progressive]],
  [],
  [],
  [$
      lambda x lambda y lambda e. op("eat")(e) and op("agent")(e,x) and op("patient")(e,"fish")
      :\
      #UPARGSIGMA[subj] multimap (#UPSIGMA #FEAT[event]) multimap #UPSIGMA
    $],
)

== Questions
"Within the class of interrogative clauses, languages typically distinguish two subtypes: those for which the information requested is a simple affirmation or disaffirmation (yes or no), and those for which the requested information is a more elaborate locution - a phrase, a proposition, or an entire discourse" #cite(<payne_describing_1997>, supplement: [p. 295]).


=== Polar questions
Polar questions are, in simple terms, "interrogative
clauses for which the expected answer is either 'yes' or 'no'" #cite(<payne_describing_1997>, supplement: [p. 295]).

Polar questions are marked by the obligatory clitic #LL[nu-] (glossed as #q for "question") attached to the first word of the clause, no matter its category. For instance,
#numbered-example(
  (
    source: ([Nu-kurumakepa?],),
    morphemes: ([#q\-drink.mead.#npst.#real],),
    translation: [Do you drink mead?],
  ),
)

==== Indirect polar questions
#numbered-example(
  (
    source: ([Lis], [kàrì], [nu=wèrà], [mùmùgedia]),
    morphemes: ([Lis], [ask.#npst.#real], [#q=queen], [eat.fish.#pfv.#pst]),
    translation: [Lis asks if the queen ate fish.],
  ),
  label: "indirectpolar1",
)

If the syllable after *nu-* has primary or secondary stress, then the clitic must harmonize (eg #LL[nù-kùng], not #LL[\*nu-kùng])

==== #THEX
#LL[nu-] being attached as a prefixed clitic to the first word of the sentence conveniently places it in the exact spot we would expect an item of category C; its use as a complementizer for indirect questions only strengthens this idea. @indirectpolar1 can be easily modeled by the following syntax tree:

#image("res/indirectquestion.png", width: 65%)

Which is licensed by PSRs as follows:

#PSR(2, 3)[C][I][#UPDOWN][#UPDOWN][#xhead][#intarg]

#PSR(2, 3)[V][C][#UPDOWN][#UPDOWNARG[xcomp]][#xhead][#intarg]

As we shall see in the section on other complement subordinate clauses, such as indirect quotes, these PSRs are general enough to apply to them as well.

=== Content questions
#cite(<payne_describing_1997>, form: "prose", supplement: [p. 299]) defines content questions as "Questions that expect a more elaborate response than simply an affirmation or disaffirmation." In other words, content questions denotationally elicit specific types of information, such as "who" or "what" or "how." They may often be responded with full sentences.

== Motion
- Default verb go/come unmarked for direction (cannot stand alone, requires PP or here/there adverb)
- Otherwise, manner in main verb and direction in PP

== Possession
=== Attributive possession
Assuming that alienable and inalienable possession is in fact "a purely lexical classification of nouns" #cite(<wals-alienable-possession>, supplement: [§3]), we can posit the existence of three classes of possessed nouns based on their behavior when serving as objects:
+ Those which behave in the normal attributive possession construction when serving as patients
+ Those which exhibit ditransitive-like behavior
+ Those which participate in types I and II of the noun incorporation system.

=== Predicative possession

== Subordinate clauses

=== Indirect speech
Complementizer #LL[ro-]

#numbered-example((
  source: ([Èbèr], [kèbèrà], [ro=kung], [kèjèbùnà], [wofu]),
  morphemes: (
    [Èbèr],
    [say.#npst.#real],
    [that=woman],
    [gather.#npst.#real],
    [sawdust],
  ),
  translation: [Èbèr says the woman is gathering the sawdust.],
  //  label: "indirectpolar1"
))


#include "chapters/verbal_paradigm.typ"

// #include "chapters/reflections.typ"

#bibliography(
  "Bibliography.bib",
  full: false,
  style: "american-psychological-association",
  title: auto,
)
