#import "Conlang Template.typ": *
#import "@preview/leipzig-glossing:0.5.0": *
#import abbreviations: *
#import "my-abbreviations.typ": *

#show: doc => conf(
  doc,
  title: "Grammar of Proto-Lisian",
  subtitle: none,
  author: "StarDolphin5",
)

// ---------- CONTENT -----------
Copyright ©2025 by StarDolphin5. Available under a Creative Commons Attribution International (CC BY) 4.0 license (#link("https://creativecommons.org/licenses/by/4.0/")[link]). You are free to: Share — copy and redistribute the material in any medium or format; Adapt — remix, transform, and build upon the material; under the following terms:

- Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

#strong[Version 0.5.1] | Last updated on 2025-07-24

This grammar was made based on the "Conlang Grammar Template" by author J Rain De Jager, released in 2019 under a Creative Commons CC BY 4.0 license, which can be found on #link("https://www.overleaf.com/latex/templates/conlang-grammar-template/ysvrsjwftmfx").


= Introduction <introduction>
Proto-Lisian is a conlang serving as the ancestor of a family of languages
originating in the midlands of the largest continent in my worldbuilding project
with working name of Minglis.

The choice of the name "Proto-Lisian" is admittedly potentially problematic,
as the modern-day Lisians are only one of the groups that spawned from the original speakers,
and that the most culturally dominant group.
Furthermore, Lisians don't identify by ethnicity but by covenantal religion,
and in that framework,
there are thousands of Lisians who don't natively speak any descendant of Proto-Lisian,
and thousands of Proto-Lisian-descendant vernacular speakers who are not "Lisians".
However, I make this choice because Proto-Lisian is the ancestor to Classical Lisian,
the scriptural, liturgical, and literary language of the Lisians;
given this is a worldbuilding project,
the choice of name is therefore overtly in service
of highlighting the Lisians' narrative prominence.

I can also be found as #link("https://www.reddit.com/user/MinervApollo/")[u/MinervApollo] on Reddit.

== Introduction to speakers
#lorem(15)

Linguistic and anthropological evidence suggests speakers of Proto-Lisian, like some of their modern counterparts, had fishing as a main economic activity and source of food.

== Theoretical framework
I am heavily indebted to #cite(<payne_describing_1997>, form: "prose") in the methodology for the layout of the grammar
and what aspects of morphosyntax to pay attention to.

I adopt a Lexical Functional approach to morphosyntax,
for which I refer to #cite(<dalrymple_handbook_2023>, form: "prose") as a general overview.
For the annotated phrase structure rules and phrase structure trees,
I use #cite(<lowe_minimal_2020>, form: "prose")'s Minimal Phrase Structure.
I will also be making use of constructions as templates
following #cite(<asudeh_constructions_2013>, form: "prose")'s proposal.
For these constructions, I assume non-compositional meaning
to be distributed among all the lexical entries generated by the lexicon,
but for objections to this treatment, see Findlay (2023).

About information structure,
I will not go beyond my limits,
adopting wholesale both #cite(<gundel_cognitive_1993>, form: "prose")'s givenness hierarchy and #cite(<dalrymple_objects_2011>, form: "prose", supplement: [section 4.3])'s four-way distinction in information structure roles at s-structure and i-structure (through the features #FEAT[giv] and #FEAT[df], respectively) as sufficient for my description.
A synthesis framework for information structure granularity is theoretically appropriate
but beyond the scope of my knowledge;
I suggest #cite(<dalrymple_oxford_2019>, form: "prose", supplement: [Ch. 10]) for a deeper discussion.

Finally, I adopt Glue semantics account of argument structure,
as analyzed in #cite(<asudeh_flexible_2012>, form: "prose")
and reviewed in #cite(<jamie_y_findlay_argument_2023>, form: "prose", supplement: "Chapter 6, Section 6.3").

== Structure of this grammar
Most sections of this document are divided into two parts: a main, descriptive section,
which should be relatively accessible to anyone familiar with conlanging
or linguistic conventions like the International Phonetic Alphabet (IPA)
and the Leipzig Glossing Rules;
and a "#THEX" subsection,
where I go in depth into the formal analysis using the theoretical framework given above.
This latter subsection is not required or expected
to be read by the casual peruser
and serves mainly as a playground to test my own theoretical understanding.
However, those interested in the topic are welcome and invited to engage with it,
for which I will devote a chapter to introduce the key concepts.

In #strong[@phonology], I give an overview of the phonological inventory of Proto-Lisian and the rules of word formation,
otherwise known as phonotactics.
It also introduces the orthography used throughout the rest of the grammar.

In #strong[@syntax], the main section of this grammar,
I go not only into word order
but explore the main constructions used in the language
to express a wide range of meanings.

#include "chapters/phonology.typ"

#include "chapters/syntax.typ"

#include "chapters/verbal_paradigm.typ"

// #include "chapters/reflections.typ"

#bibliography(
  "Bibliography.bib",
  full: false,
  style: "american-psychological-association",
  title: auto,
)
